spring:
  application:
    name: lexiconmeum

app:
  load:
    data-file: file:/opt/lexiconmeum/data/lexicalData.jsonl
    parse-mode: LENIENT

  text-search:
    default-limit: 50
    result-limit-max: 50

api:
  base-path: /api/v1

server:
  port: 8085

logging:
  level:
    root: INFO